version: '3.7'
services:

  proxy:
    hostname: spiritmight_proxy
    build:
      dockerfile: Dockerfile
      context: .
    image: doctress/spiritmight:dev
    restart: always
    environment:
      - API_KEY=${API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=False
      # Prefix for redis
      - ENVIRONMENT=rgapi
      # Extra duration added onto bucket length in seconds
      - EXTRA_LENGTH=0.5
      - INTERNAL_DELAY=0
      # Testing for mocking
      #- API_URL="http://mock_api/([a-z12]{2,8})(.*)"
    ports:
      - "0.0.0.0:8888:8888"

  ### Storage
  redis:
    hostname: redis
    image: redis:7.0-rc
    restart: always

networks:
  default:
    name: spiritmight
    driver: bridge
