apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        service: redis
      name: redis
    spec:
      replicas: 1
      selector:
        matchLabels:
          service: redis
      template:
        metadata:
          labels:
            service: redis
        spec:
          containers:
            - name: redis
              image: redis:7.0-rc
              ports:
                - containerPort: 6379
                  name: redis-port
  - apiVersion: v1
    kind: Service
    metadata:
      name: redis
      labels:
        service: redis
    spec:
      type: LoadBalancer
      ports:
        - port: 6379
          name: redis
      selector:
        service: redis
